### ISSUE TITLE
Right image rotated

### ISSUE THREAD

**Issue by annanya-tamu** [bdaiinstitute/spot_ros2#341]
For some reason, the image I am receiving from the right camera (/camera/right/image) is coming flipped 180deg. Has anyone else experienced this?

**Comment by khughes-bdai** [comment]
Hi, this is expected behavior! This is because of the way the cameras are physically mounted onto Spot. If you launch the driver with RViz, you can see that the parent tf frame of the right image (/right) is rotated almost upside-down when compared to the parent of the left image (/left). 

Here's what they should look like:
![image](https://github.com/bdaiinstitute/spot_ros2/assets/157421702/126df5f2-9830-48dd-8ce4-95356209bbde)

You might also notice that the frontleft and frontright cameras are rotated too, and this is because they are placed almost vertically on the front of Spot. We are working on an addition to the driver that will stitch these front two images together and give a non-rotated image.

**Comment by annanya-tamu** [comment]
Ah I see, thanks for the explanation!
