### ISSUE TITLE
Transform errors upon launching driver

### ISSUE THREAD

**Issue by ryan-roche** [bdaiinstitute/spot_ros2#414]
I'm noticing that there are some frame transform errors that get spit out when you launch the driver. I followed the instructions on the repo, and the trigger services (`power_on`, `sit`, `stand`, etc.) work, so I'm not sure what's causing those messages.
![image](https://github.com/bdaiinstitute/spot_ros2/assets/48164514/ea71ea2a-6448-453d-a9b9-6b75a40a3ea3)

**Comment by khughes-bdai** [comment]
A few of these error messages are expected when the image publisher plugins boot up. Sometimes they get initialized slightly before the tf publishers do (since the order in which nodes get launched in ROS launchfiles is somewhat arbitrary), so they are looking for frames that momentarily don't exist.
