### ISSUE TITLE
error when launching the camera in spot

### ISSUE THREAD

**Issue by JiaheXu** [bdaiinstitute/spot_ros2#508]
Hi BDAI,

I am using a gripperless version SPOT, I am trying to get the depth and rgb camera output from spot, but it shows `Failed to get images: Failed to get images: 6(STATUS_UNSUPPORTED_PIXEL_FORMAT_REQUESTED): ImageResponse ::bosdyn::common::Status unsuccessful`, how I fix this?

Best,
Jiahe

**Comment by khughes-bdai** [comment]
Hi!
Are you using a custom gripperless firmware release from BD on your robot? If so, we have a parameter `gripperless` that can be set in your config yaml. The current behavior is that it will not bring up gripper related actions and services from the spot driver. I think currently this change is not in our image publishing stack, and the error is because images are being requested from the non-existent gripper camera. cc @tcappellari-bdai
